/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DayUI: typeof import('./src/components/EasyCron/tabs/DayUI.vue')['default']
    EasyCronInner: typeof import('./src/components/EasyCron/EasyCronInner.vue')['default']
    EasyCronInput: typeof import('./src/components/EasyCron/EasyCronInput.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HourUI: typeof import('./src/components/EasyCron/tabs/HourUI.vue')['default']
    MinuteUI: typeof import('./src/components/EasyCron/tabs/MinuteUI.vue')['default']
    MonthUI: typeof import('./src/components/EasyCron/tabs/MonthUI.vue')['default']
    PiniaLogo: typeof import('./src/components/PiniaLogo.vue')['default']
    SecondUI: typeof import('./src/components/EasyCron/tabs/SecondUI.vue')['default']
    WeekUI: typeof import('./src/components/EasyCron/tabs/WeekUI.vue')['default']
    YearUI: typeof import('./src/components/EasyCron/tabs/YearUI.vue')['default']
  }
}
